name: Hex Context Toolkit
description: Upload external context to Hex
inputs:
  publish:
    description: Publish guides automatically when the action runs on a push event. If false, a preview is created but not published.
    default: "true"
  comment_on_pr:
    description: |
      If true, comments on GitHub pull requests with a link to the context preview. Requires a `GITHUB_TOKEN` environment variable with the pull-requests: write permission.
    default: "false"
  config_file:
    description: Path to the hex_context.config.json file.
    default: ./hex_context.config.json
  token:
    description: A token with write access to Hex
    required: true
  hex_url:
    description: The URL of the Hex instance
    default: https://app.hex.tech

runs:
  using: node24
  main: dist/index.js
